### ISSUE TITLE
typechain-types missing

### ISSUE THREAD

**Issue by maximedotair** [aave/aave-sandbox#2]
$ npm run node:fork:polygon-v3

> node:fork:polygon-v3
> FORK=polygon MARKET=polygon-v3 npm run node

> node
> npx hardhat node

An unexpected error occurred:

config/types.ts:95:72 - error TS2307: Cannot find module './../typechain-types/@aave/core-v3/contracts/misc/AaveProtocolDataProvider' or its corresponding type declarations.

95 export { AaveProtocolDataProvider as AaveProtocolDataProviderV3 } from "./../typechain-types/@aave/core-v3/contracts/misc/AaveProtocolDataProvider";
                                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
config/types.ts:96:72 - error TS2307: Cannot find module './../typechain-types/@aave/protocol-v2/contracts/misc/AaveProtocolDataProvider' or its corresponding type declarations.

96 export { AaveProtocolDataProvider as AaveProtocolDataProviderV2 } from "./../typechain-types/@aave/protocol-v2/contracts/misc/AaveProtocolDataProvider";

**Comment by emmaguo13** [comment]
For anyone experiencing this error, I fixed it by commenting out all of the imported modules requiring the typechain-types folder, and compiled all of the contracts with npm run compile. The typechain-types folder was then generated and I uncommented all of the previous comments I made, allowing me to start a node.

**Comment by bvdaniel** [comment]
It also works running `npm run compile` before `npm run node:fork:polygon-v3` without commenting the code.
