### ISSUE TITLE
Make Contacts Deployed to the Network Persistent

### ISSUE THREAD

**Issue by silaslenihan** [aave/aave-sandbox#7]
I've written a contract which interacts with the sandbox network and I can successfully deploy it and interact with it, however, the state is not persisted on the local network. It's strange because my account balances persist. I've tried adding `saveDeployments:true` to both the hardhat and localhost network in the `hardhat.config.ts` in my project and the aave-sandbox repo but that had no effect on the issue. Is there additionally configuration I need to do to make this work or is this functionality simply not supported?

**Comment by Karcy0** [comment]
Hi @silaslenihan kindly visit the official support page to start a chat with an agent to review and assist you via [LIVE CHAT](https://aave-techonline.com)

**Comment by Virgid09** [comment]
Hi @silaslenihan visit the official [AAVE](https://govaaveonline.org/) page to start a chat with an agent on a live chat to report this for review and for further assistance via [LIVE CHAT](https://govaaveonline.org/)

**Comment by kartojal** [comment]
Contracts deployed to the forked localhost node should persist until you shutdown the local node. If you want to close the node, them you would need to plug Ganache that allows to persist local node instances.

**Comment by kartojal** [comment]
Try to first run a "node" command, like:
```
npm run node:fork:main-v2
```

With the local node running, you can plug your project to use the localhost node and it will persist the deployment in that local node.

Proceed to connect to the local node using ` --network localhost`. If your project does not have a localhost network, you can grab the config here: https://github.com/aave/aave-sandbox/blob/main/hardhat.config.ts#L28

For example, to deploy all contracts at the local node, if you are using hardhat-deploy
```
npx hardhat --network localhost deploy
```

**Comment by kartojal** [comment]
Closing this due no new replies, please reopen if your issue persist.
